### ISSUE TITLE
Change User ID data type from GUID to Int32 for consistency.

### ISSUE THREAD

**Issue by SonnyRR** [softuni-csharp-databases/TrekkShare#2]
Няма ли да е по-добре за консистенция да ползваме или само GUID-и или само INT за идентификатори ? С колегите се разбрахме да ползваме INT за Id колоните.

**Comment by StoyanShopov** [comment]
Няма да бъде добра идея да се използва за модела User, Primary Key - int. Можеш с два опита, да нацелиш Id-то на някой User. Тук бихме предпочели да изпозлваме GUID. От друга страна, примерно за пещерите няма да е проблем да изпозлва PK int. В ASP.NET Core е имплементирано по този начин и не мисля, че ще изгубим консистенция.
