### ISSUE TITLE
Most of the caves are not in the towns

### ISSUE THREAD

**Issue by StoyanShopov** [softuni-csharp-databases/TrekkShare#20]
Most of the caves are not in the towns. That's way we can create new table which holds latitude and longitude. We can use it for the Cottages as well.

![image](https://user-images.githubusercontent.com/25417032/53699789-a620e900-3df4-11e9-8803-04e58d5b25fe.png)

**Comment by ReginaUzunova** [comment]
Isn't it better each model to have one property IPoint Location with pair of latitude and longitude?
