### ISSUE TITLE
We have two one-to-one relationships

### ISSUE THREAD

**Issue by StoyanShopov** [softuni-csharp-databases/TrekkShare#21]
![image](https://user-images.githubusercontent.com/25417032/53699826-162f6f00-3df5-11e9-9eb3-fb8efe5d527f.png)

**Comment by AJMitev** [comment]
Is it acceptable to remove HighestPeak from Mountain model?

**Comment by StoyanShopov** [comment]
I think so. We can make HighestPeak, calcucated property and when we need it, we will send query to the db.
