### ISSUE TITLE
Should a route pass through several mountains ?

### ISSUE THREAD

**Issue by SonnyRR** [softuni-csharp-databases/TrekkShare#22]
As of right now the current implementation is many-to-one. One mountain can have many routes but one route can only have one mountain. There are routes that can go through several mountains.
Let's discuss.
[Route.cs](https://github.com/softuni-csharp-databases/TrekkShare/blob/dev/TrekkShare/TrekkShare.Models/Route.cs)

**Comment by StoyanShopov** [comment]
Yes! We need mapping table RouteMountain

**Comment by SonnyRR** [comment]
Added mapping table and described relations.
