### ISSUE TITLE
Do we need Start and End point for each Route

### ISSUE THREAD

**Issue by StoyanShopov** [softuni-csharp-databases/TrekkShare#24]
![image](https://user-images.githubusercontent.com/25417032/53699992-960a0900-3df6-11e9-982f-e7a7fbca55ba.png)

**Comment by KirilPecev** [comment]
I think we should have. It is useful and will decorate our application.

**Comment by vallecbg** [comment]
I added properties for coordinates and calculated property for the distance

**Comment by StoyanShopov** [comment]
Many entities depend on latitude and longitude, such as caves, national parks, routes etc. Can we introduce new table which will hold the locations?

**Comment by AJMitev** [comment]
Like a Point, with Id, Latitude and Longitude?
